---
#
# Packages to be installed in this section are based on instructions
# from http://ubuntuforums.org/showthread.php?t=2105755
#
- name: Install Time Machine support packages
  become: yes
  become_user: root
  apt: name="{{ item }}"
  with_items:
    - netatalk
    - libc6-dev
    - avahi-daemon
    - libnss-mdns

#
# Configure network drives
#
- name: Create Time Machine mount point
  become: yes
  become_user: root
  file: path="{{ time_machine_root_dir }}" state=directory mode=0777

- name: Mount Time Machine at boot
  become: yes
  become_user: root
  mount:
    fstype: "{{ time_machine_drive_fstype }}"
    name: "{{ time_machine_root_dir }}"
    opts: "{{ time_machine_drive_opts }}"
    src: "{{ time_machine_drive }}"
    state: present
  when: time_machine_drive == "None"
  notify: Mount Time Machine partition

- name: Clear Time Machine mount
  become: yes
  become_user: root
  mount:
    fstype: "{{ time_machine_drive_fstype }}"
    name: "{{ time_machine_root_dir }}"
    opts: "{{ time_machine_drive_opts }}"
    src: "{{ time_machine_drive }}"
    state: absent
  when: time_machine_drive != "None"
  notify: Unmount Time Machine partition
